musicrecomend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from music import views
#用于前后端连接 url分发器，路由配置文件。构建起网站的目录，对于某段url该调用哪段代码。
urlpatterns = [
                  path("admin/", admin.site.urls),
                  path("", views.index, name="index"),
                  path("login/", views.login, name="login"),
                  path("register/", views.register, name="register"),
                  path("logout/", views.logout, name="logout"),
                  path("all_movie/", views.index, name="all_movie"),
                  path("music/<int:movie_id>/", views.movie, name="music"),
                  path("score/<int:movie_id>/", views.score, name="score"),
                  path("comment/<int:movie_id>/", views.make_comment, name="comment"),
                  path("like_comment/<int:comment_id>/<int:movie_id>/", views.like_comment, name="like_comment"),
                  path("unlike_comment/<int:comment_id>/<int:movie_id>/", views.unlike_comment, name="unlike_comment"),
                  path("collect/<int:movie_id>/", views.collect, name="collect"),
                  path("decollect/<int:movie_id>/", views.decollect, name="decollect"),
                  path("personal/", views.personal, name="personal"),
                  path("mycollect/", views.mycollect, name="mycollect"),
                  path("my_comments/", views.my_comments, name="my_comments"),
                  path("my_rate/", views.my_rate, name="my_rate"),
                  path("delete_comment/<int:comment_id>", views.delete_comment, name="delete_comment"),
                  path("delete_rate/<int:rate_id>", views.delete_rate, name="delete_rate"),
                  path("hot_movie/", views.hot_movie, name="hot_movie"), # 收藏最多
                  path("most_view/", views.most_view, name="most_view"),
                  path("most_mark/", views.most_mark, name="most_mark"),
                  path("latest_movie/", views.latest_movie, name="latest_movie"),
                  # path("mark_sort/", views.mark_sort, name="mark_sort"),
                  path("search/", views.search, name="search"),
                  path("all_tags/", views.all_tags, name="all_tags"),
                  path("one_tag/<int:one_tag_id>/", views.one_tag, name="one_tag"),
                  path("choose_tags/", views.choose_tags, name="choose_tags"),
                  path("director_movie/<str:director_name>", views.director_movie, name="director_movie"),
                  path("user_recommend/", views.user_recommend, name="user_recommend"),#用户推荐
                  path("item_recommend/", views.item_recommend, name="item_recommend"),#物品推荐
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

admin.site.site_header = '推荐系统后台管理'
admin.site.index_title = '首页-推荐系统'
admin.site.site_title = '推荐系统'

music/models.py
from datetime import datetime
from datetime import date
from django.db import models
from django.db.models import Avg
from django.db.models.fields.files import FileField
from itertools import chain
#数据库表 模型是数据的唯一的、权威的信息源，包含你所存储数据的必要字段和行为 每个模型对应数据库中唯一的一张表
class User(models.Model):#用户数据表
    username = models.CharField(max_length=255, unique=True, verbose_name="账号")#unique唯一（不重复）
    password = models.CharField(max_length=255, verbose_name="密码")#CharField通常用于存储小的字符串，如名字、姓氏等。
    email = models.EmailField(verbose_name="邮箱")
    created_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "用户"
        verbose_name = "用户"

    def __str__(self):
        return self.username


class Tags(models.Model):#标签数据表
    name = models.CharField(max_length=255, verbose_name="标签", unique=True)

    class Meta:
        verbose_name = "标签"
        verbose_name_plural = "标签"

    def __str__(self):
        return self.name


class UserTagPrefer(models.Model):#存储用户选择的标签数据
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, blank=True, verbose_name="用户id",
    )
    tag = models.ForeignKey(Tags, on_delete=models.CASCADE, verbose_name='标签名')
    score = models.FloatField(default=0)

    class Meta:
        verbose_name = "用户偏好"
        verbose_name_plural = "偏好"

    def __str__(self):
        return self.user.username + str(self.score)


class Movie(models.Model):#音乐数据表
    tags = models.ManyToManyField(Tags, verbose_name='标签', blank=True)#多对多关系
    collect = models.ManyToManyField(User, verbose_name="收藏者", blank=True)
    name = models.CharField(verbose_name="歌曲名称", max_length=255, unique=True)
    director = models.CharField(verbose_name="歌手", max_length=255)
    country = models.CharField(verbose_name="国家/地点", max_length=255)
    years = models.DateField(verbose_name='发型时间')
    leader = models.CharField(verbose_name="专辑名称", max_length=1024)
    d_rate_nums = models.IntegerField(verbose_name="评价数")
    d_rate = models.CharField(verbose_name="评分", max_length=255)
    intro = models.TextField(verbose_name="描述")
    num = models.IntegerField(verbose_name="浏览量", default=0)
    origin_image_link = models.URLField(verbose_name='图片地址', max_length=255, null=True)
    image_link = models.FileField(verbose_name="封面图片", max_length=255, upload_to='music_cover')
    imdb_link = models.URLField(null=True)

    @property
    def movie_rate(self):
        movie_rate = Rate.objects.filter(movie_id=self.id).aggregate(Avg('mark'))['mark__avg']
        return movie_rate or '无'

    class Meta:
        verbose_name = "音乐"
        verbose_name_plural = "音乐"

    def __str__(self):
        return self.name

    def to_dict(self, fields=None, exclude=None):
        opts = self._meta
        data = {}
        for f in chain(opts.concrete_fields, opts.private_fields, opts.many_to_many):
            if exclude and f.name in exclude:
                continue
            if fields and f.name not in fields:
                continue
            value = f.value_from_object(self)
            if isinstance(value, date):
                value = value.strftime('%Y-%m-%d')
            elif isinstance(f, FileField):
                value = value.url if value else None
            data[f.name] = value
        return data

#用户对音乐打分数据
class Rate(models.Model):
    movie = models.ForeignKey(
        Movie, on_delete=models.CASCADE, blank=True, null=True, verbose_name="音乐id"
    )
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, blank=True, null=True, verbose_name="用户id",
    )
    mark = models.FloatField(verbose_name="评分")
    create_time = models.DateTimeField(verbose_name="发型时间", auto_now_add=True)

    @property
    def avg_mark(self):
        average = Rate.objects.all().aggregate(Avg('mark'))['mark__avg']#求平均分
        return average

    class Meta:
        verbose_name = "评分信息"
        verbose_name_plural = verbose_name

#音乐评论表
class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="用户")#外建关联
    content = models.CharField(max_length=255, verbose_name="内容")
    create_time = models.DateTimeField(auto_now_add=True)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, verbose_name="音乐")

    class Meta:
        verbose_name = "评论"
        verbose_name_plural = verbose_name


class LikeComment(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, verbose_name='评论')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='用户')

    class Meta:
        verbose_name = "评论点赞"
        verbose_name_plural = verbose_name

music/views.py
import json
import random
from functools import wraps

from django.core.cache import cache
from django.core.paginator import Paginator
from django.db.models import Q, Count
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from rest_framework.renderers import JSONRenderer

from cache_keys import USER_CACHE, ITEM_CACHE
from recommend_music import recommend_by_user_id, recommend_by_item_id
from .forms import *
#前端与数据库的连接

def movies_paginator(movies, page):#分页    第一个参数：对象列表，第二个参数：每页显示的条数
    paginator = Paginator(movies, 12)
    if page is None:
        page = 1
    movies = paginator.page(page)
    return movies


# from django.urls import HT
# json response
class JSONResponse(HttpResponse):#修改返回的数据类型
    def __init__(self, data, **kwargs):
        content = JSONRenderer().render(data)#将ReturnDict字典类型转换为字节流
        kwargs["content_type"] = "application/json;"
        super(JSONResponse, self).__init__(content, **kwargs)


# 登录功能
def login(request):
    if request.method == "POST":#post是向服务器提交数据，数据放置在容器
        form = Login(request.POST)
        if form.is_valid():#在获取反序列化的数据前，必须调用is_valid()方法进行验证，验证成功返回True，否则返回False
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            result = User.objects.filter(username=username)#filter方法是从数据库的取得匹配的结果，返回一个对象列表
            if result:
                user = User.objects.get(username=username)#get是从数据库的取得一个匹配的结果 返回一个对象
                if user.password == password:
                    request.session["login_in"] = True#允许登录
                    request.session["user_id"] = user.id#请求参数
                    request.session["name"] = username
                    # 用户第一次注册，需要选标签
                    new = request.session.get('new')#两个都是基于sessions.Session发送请求的，session.get不关闭连接
                    if new:
                        tags = Tags.objects.all()
                        print('goto choose tag')
                        return render(request, 'choose_tag.html', {'tags': tags})
                    return redirect(reverse("index"))
                else:
                    return render(
                        request, "login.html", {"form": form, "message": "密码错误"}
                    )
            else:
                return render(
                    request, "login.html", {"form": form, "message": "账号不存在"}
                )
    else:
        form = Login()
        return render(request, "login.html", {"form": form})


# 注册功能
def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        error = None
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password2"]
            email = form.cleaned_data["email"]
            User.objects.create(
                username=username,
                password=password,
                email=email,
            )
            request.session['new'] = 'true'
            # 根据表单数据创建一个新的用户
            return redirect(reverse("login"))  # 跳转到登录界面
        else:
            return render(
                request, "register.html", {"form": form, "error": error}
            )  # 表单验证失败返回一个空表单到注册页面
    form = RegisterForm()
    return render(request, "register.html", {"form": form})


def logout(request):
    if not request.session.get("login_in", None):  # 不在登录状态跳转回首页
        return redirect(reverse("index"))
    request.session.flush()  # 清除session信息
    print('注销')
    return redirect(reverse("index"))


def login_in(func):  # 验证用户是否登录
    @wraps(func)
    def wrapper(*args, **kwargs):
        request = args[0]
        is_login = request.session.get("login_in")
        if is_login:
            return func(*args, **kwargs)
        else:
            return redirect(reverse("login"))

    return wrapper


# Create your views here.
#主页左侧的音乐显示
def index(request):
    order =  request.POST.get("order") or request.session.get('order')
    request.session['order']=order
    if order == 'collect':
        movies = Movie.objects.annotate(collectors=Count('collect')).order_by('-collectors')#按收藏数降序排列
        print(movies.query)
        title = '收藏排序'
    elif order == 'rate':
        movies = Movie.objects.all().annotate(marks=Avg('rate__mark')).order_by('-marks')
        title = '评分排序'
    elif order == 'years':
        movies = Movie.objects.order_by('-years')
        title = '时间排序'
    else:
        movies = Movie.objects.order_by('-num')
        title = '热度排序'
    paginator = Paginator(movies, 8)
    new_list = Movie.objects.order_by('-years')[:8]#每页显示8条
    current_page = request.GET.get("page", 1)
    movies = paginator.page(current_page)
    return render(request, 'items.html', {'movies': movies, 'new_list': new_list, 'title': title})#跳转到对应html文件

#音乐详情
def movie(request, movie_id):
    movie = Movie.objects.get(pk=movie_id)
    movie.num += 1
    movie.save()
    comments = movie.comment_set.order_by("-create_time")#音乐评论
    user_id = request.session.get("user_id")
    movie_rate = Rate.objects.filter(movie=movie).all().aggregate(Avg('mark'))#音乐评分 实现数据拆分成组并分别计算平均数的操作
    if movie_rate:
        movie_rate = movie_rate['mark__avg']
    else:
        movie_rate = 0
    if user_id is not None:
        user_rate = Rate.objects.filter(movie=movie, user_id=user_id).first()
        user = User.objects.get(pk=user_id)
        is_collect = movie.collect.filter(id=user_id).first()
    return render(request, "music.html", locals())


def search(request):  # 搜索
    if request.method == "POST":  # 如果搜索界面
        key = request.POST["search"]
        request.session["search"] = key  # 记录搜索关键词解决跳页问题
    else:
        key = request.session.get("search")  # 得到关键词
    movies = Movie.objects.filter(
        Q(name__icontains=key) | Q(intro__icontains=key) | Q(director__icontains=key)
    )  # 进行内容的模糊搜索
    page_num = request.GET.get("page", 1)
    movies = movies_paginator(movies, page_num)
    return render(request, "items.html", {"movies": movies, 'title': '搜索结果'})

#所有标签
def all_tags(request):
    tags = Tags.objects.all()
    return render(request, "all_tags.html", {'all_tags': tags})

#点击一个标签
def one_tag(request, one_tag_id):
    tag = Tags.objects.get(id=one_tag_id)
    movies = tag.movie_set.all()
    page_num = request.GET.get("page", 1)
    movies = movies_paginator(movies, page_num)
    return render(request, "items.html", {"movies": movies, 'title': tag.name})

#收藏最多
def hot_movie(request):
    page_number = request.GET.get("page", 1)#分页
    movies = Movie.objects.annotate(user_collector=Count('collect')).order_by('-user_collector')[:10]#查出所有电影，按收藏人数排序
    movies = movies_paginator(movies[:10], page_number)
    return render(request, "items.html", {"movies": movies, "title": "收藏最多"})#返回给items.html


# 评分最多
def most_mark(request):
    page_number = request.GET.get("page", 1)
    movies = Movie.objects.all().annotate(num_mark=Count('rate')).order_by('-num_mark')
    movies = movies_paginator(movies, page_number)
    return render(request, "items.html", {"movies": movies, "title": "评分最多"})


# 浏览最多
def most_view(request):
    page_number = request.GET.get("page", 1)
    movies = Movie.objects.annotate(user_collector=Count('num')).order_by('-num')
    movies = movies_paginator(movies, page_number)
    return render(request, "items.html", {"movies": movies, "title": "浏览最多"})

#最新音乐
def latest_movie(request):
    movie_list = Movie.objects.order_by("-years")[:10]
    json_movies = [movie.to_dict(fields=['name', 'image_link', 'id', 'years', 'd_rate']) for movie in movie_list]
    return HttpResponse(json.dumps(json_movies), content_type="application/json")


# 某个歌手的音乐
def director_movie(request, director_name):
    page_number = request.GET.get("page", 1)
    movies = Movie.objects.filter(director=director_name)
    movies = movies_paginator(movies, page_number)
    return render(request, "items.html", {"movies": movies, "title": "{}的音乐".format(director_name)})

#修改个人信息
@login_in
def personal(request):
    user = User.objects.get(id=request.session.get("user_id"))
    if request.method == "POST":
        form = Edit(instance=user, data=request.POST)
        if form.is_valid():#验证信息格式
            form.save()
            request.session['name'] = user.username
            return render(
                request, "personal.html", {"message": "修改成功!", "form": form, 'title': '我的信息', 'user': user}
            )
        else:
            return render(
                request, "personal.html", {"message": "修改失败", "form": form, 'title': '我的信息', 'user': user}
            )
    form = Edit(instance=user)
    return render(request, "personal.html", {"user": user, 'form': form, 'title': '我的信息'})


@login_in
@csrf_exempt
def choose_tags(request):
    tags_name = json.loads(request.body)
    user_id = request.session.get('user_id')
    for tag_name in tags_name:
        tag = Tags.objects.filter(name=tag_name.strip()).first()
        UserTagPrefer.objects.create(tag_id=tag.id, user_id=user_id, score=5)
    request.session.pop('new')
    return redirect(reverse("index"))


@login_in
# 给音乐进行评论
def make_comment(request, movie_id):
    user = User.objects.get(id=request.session.get("user_id"))
    movie = Movie.objects.get(id=movie_id)
    comment = request.POST.get("comment")
    Comment.objects.create(user=user, movie=movie, content=comment)
    return redirect(reverse("music", args=(movie_id,)))#用于重定向 刷新


@login_in
# 展示我的评论的地方
def my_comments(request):
    user = User.objects.get(id=request.session.get("user_id"))
    comments = user.comment_set.all()
    print('comment:', comments)
    return render(request, "my_comment.html", {"item": comments})


# 给评论点赞
@login_in
def like_comment(request, comment_id, movie_id):
    user_id = request.session.get("user_id")
    LikeComment.objects.get_or_create(user_id=user_id, comment_id=comment_id)#查询或者创建一条数据，首先是执行的时候首先会去查询有没有这个值，如果有就返回，没有就创建

templates/all_tags.html
<!--标签页面-->
{% extends "base.html" %}
{% block main_content %}
    <div class="wrap-content">
        <div class="movie">
            <div class="row type">
                <div class="title">
                    <center><h2>Classification</h2></center>
                </div>
            </div>
            <div class="row">
                {% for tag in all_tags %}
                    <div class="col-1-4">
                        <div class="wrap-col">
                            <div class="post">
                                <div class="view effect">
                                    <div class="mask">
                                        <a href="{% url 'one_tag' tag.id %}" class="info"></a>
                                    </div>
                                </div>
                                <div class="clear"></div>
                                <a href="{% url 'one_tag' tag.id %}"><h3>{{ tag.name }}</h3></a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/base_show.html
{% extends 'base.html' %}
{% block main_content %}
    <table class="table">
        <thead>
        <tr>
            {% block th_name %}
            {% endblock %}
        </tr>
        </thead>
        <tbody>
        {% for i in item %}
            <div class="modal" id="confirm-modal">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-footer">
                        <div class="row">
                            <div class="col-md-6">
                                                           <button type="button" class="btn btn-block btn-default" data-dismiss="modal">不确认</button>
                            </div>
                            <div class="col-md-6">
                                   {% block modal %}
                            {% endblock %}
                            </div>
                        </div>

                        </div>
                    </div>
{#                </div>#}
            </div>
            <tr>
                {% block th_value %}
                {% endblock %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <!-- Button trigger modal -->
    <!-- Modal -->
{% endblock %}

templates/music.html
<!--音乐页面-->
{% extends "base.html" %}
{% load grav_tag %}
{% load is_like %}
{% block main_content %}
    <div class="wrap-content">
        <article>
            <div class="art-header">
                <div class="row">
                    <div class="col-md-3 " style="margin-bottom: 10px ;margin-top: 10px">
                        <img src="{{ MEDIA_URL }}{{ movie.image_link }}"/>
                    </div>
                    <div class="col-md-9">
                        <div class="wrap-col" style="overflow: auto">
                            <ul class="movie-info" style="overflow: auto">
                                <div class="row">
                                    <div class="col-md-6">
                                        <p>name: <a href="#">{{ movie.name }}</a></p>
                                    </div>
                                    <div class="col-md-6">
                                        <p>Time of issue: <a href="#">{{ movie.years }}</a></p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <p>歌手: <a href="#">{{ movie.director }}</a></p>
                                    </div>
                                    <div class="col-md-6">
                                        <p>专辑名称: <a href="#">{{ movie.leader |slice:30 }}...</a></p>
                                    </div>
                                </div>
                                <li>
                                    <div class="row">
                                        <div class="col-1-3">
                                            <a target="_blank" style="display: inline-block; margin-left: 15px" class="btn-lg btn-success" href="https://y.qq.com/n/ryqq/search?w={{ movie.name }}">前往播放</a><!--需要实现点击某一文本或者元素后使得一个页面打开跳转到另一个页面的功能效果，这里就用到a herf标签属性，herf后面就是你指定跳转到的某个链接地址。-->
                                        </div>
                                    <div class="col-1-3">
                                            <a target="_blank" style="display: inline-block; margin-left: 15px" class="btn-lg btn-success" href="https://y.qq.com/n/ryqq/search?w={{ movie.director}}">歌手详细资料</a>
                                        </div>
{#                                    <div class="col-1-3">#}
{#                                            <a target="_blank" style="display: inline-block; margin-left: 15px" class="btn-lg btn-success" href="{{ movie.imdb_link}}">查看歌手</a>#}
{#                                        </div>#}
                                    <div class="col-1-3">
                                            <a target="_blank" style="display: inline-block; margin-left: 15px" class="btn-lg btn-success" href="{{ movie.imdb_link}}">查看歌手照片</a>
                                        </div>


                                        <div class="col-1-3">
                                        <br>
                                            {% if is_collect %}
                                                <a class="btn-lg btn-warning" style="display: inline-block" href="{% url 'decollect' movie.id %}">取消收藏</a>
                                            {% else %}
                                                <a class="btn-lg btn-primary" style="display: inline-block" href="{% url 'collect' movie.id %}">点击收藏</a>{% endif %}
                                        </div>
                                        <div class="col-1-3">
                                            <br>
                                            <h2 style="display: inline"> 收藏人数:{{ movie.collect.count }} </h2>
                                        </div>
                                        {#                                            <a style="display: inline-block" class="btn-lg btn-primary" href="{% url 'collect' music.id %}">收藏</a>#}
                                    </div>
                                <li>
                                </li>
                                <li style="margin-top: 20px"><p style="display: inline-block; margin-right: 15px">歌曲评分: <a href="#">{{ movie.d_rate }}</a></p>
                                    <p style="display: inline-block">标签： {% for tag in movie.tags.all %}  <a href="{% url 'one_tag' tag.id %}">{{ tag.name }}</a>{% endfor %}</p>
                                </li>
                                <li style="margin-top: 20px">
                                    {% if user_rate is not None %}
                                        <h4>您已经进行打分: {{ user_rate.mark }}</h4>
                                    {% else %}
                                        <form action="{% url 'score' movie.id %}" method="post">
                                            {% csrf_token %}
                                            <p style="display: inline-block;"> 添加评分</p>
                                            <select name="score">
                                                <option>1.0</option>
                                                <option>2.0</option>
                                                <option>3.0</option>
                                                <option>4.0</option>
                                                <option>5.0</option>
                                            </select>
                                            <button type="submit" class="button bt1">提交</button>
                                        </form>
                                    {% endif %}
                                </li>
                                                            <div class="clear"></div>

                            </ul>
                        </div>
                    </div>
                </div>
            </div>
                        <div class="clear"></div>
            <div class="art-content">
                                <div class="clear"></div>
                <p>{{ movie.intro }}</p>
                <div class="clear"></div>
            </div>
        </article>
        <div class="widget wid-related">
            <div class="wid-header">
                <div class="row">
                    <div class="col-md-9">
                        <h5>基于物品推荐歌曲</h5>
                    </div>
                    <div class="col-md-3">
                        <button class="button bt1" onclick="get_item_recommend()">换一批</button>
                    </div>
                </div>
            </div>
            <div class="wid-content">
                <div class="row" id="item-recommend">
                </div>
            </div>
        </div>
    </div>
    <div class="row clearfix">
        <div class="row">
            <div class="col-md-9">
                <form role="form" action="{% url 'comment' movie.id %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <input placeholder="快来说说点什么吧" class="form-control" name="comment" cols="10" rows="10">
                    </div>
                    <div class="form-group">
                        <button type="submit" style="float: right;" class="btn-lg btn-success">提交评论</button>
                    </div>
                </form>
            </div>
            <div class="row">
                <div class="col-md-9">
                    <h2 style="border-bottom: dashed #fcab2b 1px; padding-bottom: 10px">评论</h2>
                    <div class="item-list">
                        <ul>
                            {% for i in comments %}
                                <li class="list-item">
                                    <div class="avartar">
                                        <a><img src='{{ request.user.email|gravatar:"75" }}'> </a>
                                    </div>
                                    <div class="list-info">
                                        <p>{{ i.content }}</p>
                                        {{ i.user.username }} 发表于{{ i.create_time }} 推荐
                                    </div>
                                    {#                                    {% if  i.user | is_like:i.user.id %}#}
                                    {#                                        <a href="{% url 'unlike_comment' i.id music.id %}" class="recommend-link"><span class="fa fa-lg fa-thumbs-up"#}
                                    {#                                    {% else %}#}
                                    <a href="{% url 'like_comment' i.id movie.id %}" class="recommend-link"><span class="fa fa-lg fa-thumbs-up">({{ i.likecomment_set.count }})</span></a>
                                    {#                                    {% endif %}#}
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block bottom-js %}
    <script>
        function get_item_recommend() {
            $.ajax({
                url: '/item_recommend/',
                type: 'GET',
                success: function (result) {
                    var html = "";
                    var array_length = result.length;
                    for (var i = 0; i < array_length; i++) {
                        html += `<div class="col-1-3"><div class="wrap-col">` +
                            `<a href="/music/${result[i].id}"><img src="${result[i].image_link}"/></a>` +
                            `<a href="/music/${result[i].id}"><h4>${result[i].name}</h4></a></div></div>`;
                    }
                    $('#item-recommend').html(html);
                },
                fail: function (xhr, textStatus, errorThrown) {
                    alert('request failed');
                },
                error: function (jqXHR, exception) {
                    console.log(jqXHR.status);
                    console.log(exception);
                }
            });
        }

        get_item_recommend();
    </script>


{% endblock %}

templates/my_comment.html
<!--我的评论-->
{% extends "base_show.html" %}
{% block th_name %}
    <th>item</th>
    <th>Comments</th>
    <th>Comments time</th>
    <th>Delete</th>
{% endblock %}
{% block modal %}
    <a class="btn btn-primary btn-block" href="{% url 'delete_comment' i.id %}">确认</a>

{% endblock %}
{% block th_value %}
    <td>{{ i.movie.name }}</td>
    <td>{{ i.content }}</td>
    <td>{{ i.create_time }}</td>
    <td><a class="btn btn-danger" data-toggle="modal" data-target="#confirm-modal">删除</a></td>
{% endblock %}

templates/my_rate.html
<!--我的评分-->
{% extends "base_show.html" %}
{% block th_name %}
    <th>item</th>
    <th>score</th>
    <th>time</th>
    <th>adapt</th>
{% endblock %}
{% block modal %}
    <a class="btn btn-primary btn-block" href="{% url 'delete_rate' i.id %}">确认</a>
{% endblock %}
{% block th_value %}
    <td><a href="{% url 'music' i.movie.id %}"> {{ i.movie.name }}</a></td>
    <td>{{ i.mark }}</td>
    <td>{{ i.create_time }}</td>
    <td><a class="btn btn-danger" data-toggle="modal" data-target="#confirm-modal">删除</a></td>
{% endblock %}